services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:8000"
    depends_on:
      - web
    volumes:
      - /private/var/services/nginx/letsencrypt:/etc/letsencrypt
  web:
    build: ./web/
    command: gunicorn main:app -w 2 -b :5000
    expose:
      - 5000

volumes:
  web: